//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAndLogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class loan
    {
        public int id { get; set; }
        public long loanamont { get; set; }
        public long loanterme { get; set; }
        public long monthlyincome { get; set; }
        public int idbank { get; set; }
        public int IdUser { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual Users Users { get; set; }
    }
}
