//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAndLogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class louer
    {
        public int idlouer { get; set; }
        public string titre { get; set; }
        public string description { get; set; }
        public System.DateTime datedebut { get; set; }
        public System.DateTime datefin { get; set; }
        public int CODE_PRODUIT { get; set; }
        public string status { get; set; }
        public int IdUser { get; set; }
        public string type { get; set; }
    
        public virtual Prod Prod { get; set; }
        public virtual Users Users { get; set; }
    }
}
