//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAndLogin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyDatabaseEntities24 : DbContext
    {
        public MyDatabaseEntities24()
            : base("name=MyDatabaseEntities24")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bank> Bank { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<loan> loan { get; set; }
        public virtual DbSet<louer> louer { get; set; }
        public virtual DbSet<Prod> Prod { get; set; }
        public virtual DbSet<reclamation> reclamation { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<vente> vente { get; set; }
    }
}
