//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAndLogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prod
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prod()
        {
            this.louer = new HashSet<louer>();
            this.reclamation = new HashSet<reclamation>();
            this.vente = new HashSet<vente>();
        }
    
        public int CODE_PRODUIT { get; set; }
        public int CODE_CATEGORIE { get; set; }
        public int IdUser { get; set; }
        public string LIBELLE_PRODUIT { get; set; }
        public string DESCRIPTION_PRODUIT { get; set; }
        public string IMAGE_PRODUIT { get; set; }
        public string URL_IMAGE_PRODUIT { get; set; }
        public System.DateTime DATE_SAISIE { get; set; }
        public Nullable<double> Prix { get; set; }
        public string type { get; set; }
        public int remise { get; set; }
        public int vu { get; set; }
        public string status { get; set; }
        public System.DateTime datedebut { get; set; }
        public System.DateTime datefin { get; set; }
    
        public virtual Categories Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<louer> louer { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reclamation> reclamation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vente> vente { get; set; }
    }
}
