//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationAndLogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reclamation
    {
        public int idrec { get; set; }
        public string titrerec { get; set; }
        public string descriptionrec { get; set; }
        public System.DateTime daterec { get; set; }
        public int CODE_PRODUIT { get; set; }
        public int IdUser { get; set; }
        public string statusrec { get; set; }
    
        public virtual Prod Prod { get; set; }
        public virtual Users Users { get; set; }
    }
}
